### ISSUE TITLE
[Crash] SuperMartijn642's Core Lib update breaks your mod.

### ISSUE THREAD

**Issue by RosivDamotil** [SuperMartijn642/AdditionalLanterns#23]
With SuperMartijn642's Core lib 1.1.9-a it works fine.

**Version Info**
- Minecraft 1.19.4
- Additional Lantern 1.0.4a
- SuperMartijn642's Core lib 1.1.9-b

**Steps to Reproduce**
Start the server ;)

**Crash report (~/logs/latest.log)**
[07:15:58] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Can't change holder ResourceKey[minecraft:item / minecraft:lantern] value: existing=lantern, new=lantern
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.IllegalStateException: Can't change holder ResourceKey[minecraft:item / minecraft:lantern] value: existing=lantern, new=lantern
	at net.minecraft.class_6880$class_6883.method_45918(class_6880.java:226) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_45938(class_2370.java:356) ~[server-intermediary.jar:?]
	at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1350) ~[?:?]
	at net.minecraft.class_2370.method_40276(class_2370.java:356) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455$class_6892.method_40332(class_5455.java:41) ~[server-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5455$class_6891.<init>(class_5455.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455$class_7781.<init>(class_5455.java:105) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455.method_40316(class_5455.java:109) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.<init>(class_7780.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.method_45929(class_7780.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.method_45930(class_7780.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_7659.method_45139(class_7659.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:927) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:921) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	... 4 more

**Comment by SuperMartijn642** [comment]
Fixed in the updated version of my core library.
Thank you for reporting the issue!
